In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

from patsy import dmatrices
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_validate

import pickle

In [2]:
# read in data
df = pd.read_csv('weatheravailability.csv')

df.head(5)

,Unnamed: 0,number,last_update,available_bike_stands,available_bikes,total_bike_stands,description
0,0,2,1551726000,15,5,20,Rain
1,1,3,1551726000,19,1,20,Rain
2,2,4,1551726000,20,0,20,Rain
3,3,5,1551726000,11,29,40,Rain
4,4,6,1551726000,16,4,20,Rain

In [3]:
# want to remove the 'Unnamed: 0' column.
# to make it easier, strip the space and conver to lower case...
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

df.head(5)

,unnamed:_0,number,last_update,available_bike_stands,available_bikes,total_bike_stands,description
0,0,2,1551726000,15,5,20,Rain
1,1,3,1551726000,19,1,20,Rain
2,2,4,1551726000,20,0,20,Rain
3,3,5,1551726000,11,29,40,Rain
4,4,6,1551726000,16,4,20,Rain

In [4]:
df = df.drop('unnamed:_0', axis=1)

In [5]:
df.rename(columns={"description": "weather_desc"}, inplace=True)

In [6]:
df.head(5)

,number,last_update,available_bike_stands,available_bikes,total_bike_stands,weather_desc
0,2,1551726000,15,5,20,Rain
1,3,1551726000,19,1,20,Rain
2,4,1551726000,20,0,20,Rain
3,5,1551726000,11,29,40,Rain
4,6,1551726000,16,4,20,Rain

In [7]:
df.dtypes

number                    int64
last_update               int64
available_bike_stands     int64
available_bikes           int64
total_bike_stands         int64
weather_desc             object
dtype: object

In [8]:
continuous_features = ['available_bikes', 'available_bike_stands', 'last_update', 'total_bike_stands']

In [9]:
# categorical_features = df[['weather_desc']].columns

In [10]:
target_feature = ['available_bikes']

In [11]:
df['weather_desc'].value_counts()

Clouds     58312
Rain       23672
Drizzle     3380
Clear       3277
Mist        1921
Name: weather_desc, dtype: int64

In [12]:
# # turn the weather description values into integers for easier representation and comparison

# df['weather_desc'] = df['weather_desc'].map({'Clouds': 1, 'Rain': 2, 'Drizzle': 3, 'Clear': 4, 'Mist': 5})

In [13]:
df.head(5)

,number,last_update,available_bike_stands,available_bikes,total_bike_stands,weather_desc
0,2,1551726000,15,5,20,Rain
1,3,1551726000,19,1,20,Rain
2,4,1551726000,20,0,20,Rain
3,5,1551726000,11,29,40,Rain
4,6,1551726000,16,4,20,Rain

## UNDERSTANDING THE DATA

In [14]:
# no correlation...

df[['weather_desc', 'available_bikes', 'available_bike_stands']].corr()

                       available_bikes  available_bike_stands
available_bikes               1.000000              -0.765681
available_bike_stands        -0.765681               1.000000

## MODEL

In [15]:
# print(df.head(10))

# X = df[['weather_desc', 'last_update', 'number']]
# y = df.available_bikes

# print("\nDescriptive features in X:\n", X)
# print("\nTarget feature in y:\n", y)

In [16]:
# Use more features for training
# Train aka fit, a model using all continuous and categorical features.
weather_desc_dummies = pd.get_dummies(df['weather_desc'], prefix='weather_desc_')
print("weather_desc_dummies:", weather_desc_dummies)

categorical_features = weather_desc_dummies.columns.values.tolist()

features = continuous_features + categorical_features
print("\nCont features: ", continuous_features)
print("Categ features: ", categorical_features)
print("Features: ", features)

weather_desc_dummies:        weather_desc__Clear  weather_desc__Clouds  weather_desc__Drizzle  \
0                        0                     0                      0
1                        0                     0                      0
2                        0                     0                      0
3                        0                     0                      0
4                        0                     0                      0
5                        0                     0                      0
6                        0                     0                      0
7                        0                     0                      0
8                        0                     0                      0
9                        0                     0                      0
10                       0                     0                      0
11                       0                     0                      0
12                       0                     0                      0
13                       0                     0                      0
14                       0                     0                      0
15                       0                     0                      0
16                       0                     0                      0
17                       0                     0                      0
18                       0                     0                      0
19                       0                     0                      0
20                       0                     0                      0
21                       0                     0                      0
22                       0                     0                      0
23                       0                     0                      0
24                       0                     0                      0
25                       0                     0                      0
26                       0                     0                      0
27                       0                     0                      0
28                       0                     0                      0
29                       0                     0                      0
...                    ...                   ...                    ...
90532                    0                     1                      0
90533                    0                     1                      0
90534                    0                     1                      0
90535                    0                     1                      0
90536                    0                     1                      0
90537                    0                     1                      0
90538                    0                     1                      0
90539                    0                     1                      0
90540                    0                     1                      0
90541                    0                     1                      0
90542                    0                     1                      0
90543                    0                     1                      0
90544                    0                     1                      0
90545                    0                     1                      0
90546                    0                     1                      0
90547                    0                     1                      0
90548                    0                     1                      0
90549                    0                     1                      0
90550                    0                     1                      0
90551                    0                     1                      0
90552                    0                     1                      0
90553                    0                     1                      0
90554                    0                     1                      0
90555                    0                     1                      0
90556                    0                     1                      0
90557                    0                     1                      0
90558                    0                     1                      0
90559                    0                     1                      0
90560                    0                     1                      0
90561                    0                     1                      0

       weather_desc__Mist  weather_desc__Rain
0                       0                   1
1                       0                   1
2                       0                   1
3                       0                   1
4                       0                   1
5                       0                   1
6                       0                   1
7                       0                   1
8                       0                   1
9                       0                   1
10                      0                   1
11                      0                   1
12                      0                   1
13                      0                   1
14                      0                   1
15                      0                   1
16                      0                   1
17                      0                   1
18                      0                   1
19                      0                   1
20                      0                   1
21                      0                   1
22                      0                   1
23                      0                   1
24                      0                   1
25                      0                   1
26                      0                   1
27                      0                   1
28                      0                   1
29                      0                   1
...                   ...                 ...
90532                   0                   0
90533                   0                   0
90534                   0                   0
90535                   0                   0
90536                   0                   0
90537                   0                   0
90538                   0                   0
90539                   0                   0
90540                   0                   0
90541                   0                   0
90542                   0                   0
90543                   0                   0
90544                   0                   0
90545                   0                   0
90546                   0                   0
90547                   0                   0
90548                   0                   0
90549                   0                   0
90550                   0                   0
90551                   0                   0
90552                   0                   0
90553                   0                   0
90554                   0                   0
90555                   0                   0
90556                   0                   0
90557                   0                   0
90558                   0                   0
90559                   0                   0
90560                   0                   0
90561                   0                   0

[90562 rows x 5 columns]

Cont features:  ['available_bikes', 'available_bike_stands', 'last_update', 'total_bike_stands']
Categ features:  ['weather_desc__Clear', 'weather_desc__Clouds', 'weather_desc__Drizzle', 'weather_desc__Mist', 'weather_desc__Rain']
Features:  ['available_bikes', 'available_bike_stands', 'last_update', 'total_bike_stands', 'weather_desc__Clear', 'weather_desc__Clouds', 'weather_desc__Drizzle', 'weather_desc__Mist', 'weather_desc__Rain']

In [17]:
df_all = pd.concat([df, weather_desc_dummies], axis=1)
# print(df_all)

df_all = df_all.drop('weather_desc', axis = 1)
print(df_all)

       number  last_update  available_bike_stands  available_bikes  \
0           2   1551726000                     15                5
1           3   1551726000                     19                1
2           4   1551726000                     20                0
3           5   1551726000                     11               29
4           6   1551726000                     16                4
5           7   1551726000                      9               19
6           8   1551726000                     15               15
7           9   1551726000                      5               19
8          10   1551726000                      7                9
9          11   1551726000                     30                0
10         12   1551726000                     16                4
11         13   1551726000                     29                1
12         14   1551726000                      5               25
13         15   1551726000                     16                0
14         16   1551726000                      4               16
15         17   1551726000                     18                2
16         18   1551726000                     24                6
17         19   1551726000                     30                0
18         21   1551726000                      4               26
19         22   1551726000                      1               19
20         23   1551726000                      2               28
21         24   1551726000                     14                6
22         25   1551726000                     28                2
23         26   1551726000                      3               17
24         27   1551726000                     18                2
25         28   1551726000                     26                4
26         29   1551726000                     23                6
27         30   1551726000                     18                2
28         31   1551726000                     14                6
29         32   1551726000                      7               23
...       ...          ...                    ...              ...
90532      86   1555138800                      3               35
90533      87   1555138800                     12               26
90534      88   1555138800                      4               26
90535      89   1555138800                     38                1
90536      90   1555138800                     35                5
90537      91   1555138800                     10               20
90538      92   1555138800                      0               40
90539      93   1555138800                      0               40
90540      94   1555138800                     11               29
90541      95   1555138800                      7               33
90542      96   1555138800                     15               15
90543      97   1555138800                     13               27
90544      98   1555138800                     40                0
90545      99   1555138800                     28                2
90546     100   1555138800                      0               25
90547     101   1555138800                     22                8
90548     102   1555138800                     12               28
90549     103   1555138800                     39                1
90550     104   1555138800                     26               14
90551     105   1555138800                     25               11
90552     106   1555138800                     15               25
90553     107   1555138800                     30               10
90554     108   1555138800                     39                1
90555     109   1555138800                      9               20
90556     110   1555138800                     30               10
90557     111   1555138800                     26               14
90558     112   1555138800                      6               24
90559     113   1555138800                     40                0
90560     114   1555138800                     38                2
90561     115   1555138800                      2               28

       total_bike_stands  weather_desc__Clear  weather_desc__Clouds  \
0                     20                    0                     0
1                     20                    0                     0
2                     20                    0                     0
3                     40                    0                     0
4                     20                    0                     0
5                     28                    0                     0
6                     30                    0                     0
7                     24                    0                     0
8                     16                    0                     0
9                     30                    0                     0
10                    20                    0                     0
11                    30                    0                     0
12                    30                    0                     0
13                    16                    0                     0
14                    20                    0                     0
15                    20                    0                     0
16                    30                    0                     0
17                    30                    0                     0
18                    30                    0                     0
19                    20                    0                     0
20                    30                    0                     0
21                    20                    0                     0
22                    30                    0                     0
23                    20                    0                     0
24                    20                    0                     0
25                    30                    0                     0
26                    29                    0                     0
27                    20                    0                     0
28                    20                    0                     0
29                    30                    0                     0
...                  ...                  ...                   ...
90532                 38                    0                     1
90533                 38                    0                     1
90534                 30                    0                     1
90535                 39                    0                     1
90536                 40                    0                     1
90537                 30                    0                     1
90538                 40                    0                     1
90539                 40                    0                     1
90540                 40                    0                     1
90541                 40                    0                     1
90542                 30                    0                     1
90543                 40                    0                     1
90544                 40                    0                     1
90545                 30                    0                     1
90546                 25                    0                     1
90547                 30                    0                     1
90548                 40                    0                     1
90549                 40                    0                     1
90550                 40                    0                     1
90551                 36                    0                     1
90552                 40                    0                     1
90553                 40                    0                     1
90554                 40                    0                     1
90555                 29                    0                     1
90556                 40                    0                     1
90557                 40                    0                     1
90558                 30                    0                     1
90559                 40                    0                     1
90560                 40                    0                     1
90561                 30                    0                     1

       weather_desc__Drizzle  weather_desc__Mist  weather_desc__Rain
0                          0                   0                   1
1                          0                   0                   1
2                          0                   0                   1
3                          0                   0                   1
4                          0                   0                   1
5                          0                   0                   1
6                          0                   0                   1
7                          0                   0                   1
8                          0                   0                   1
9                          0                   0                   1
10                         0                   0                   1
11                         0                   0                   1
12                         0                   0                   1
13                         0                   0                   1
14                         0                   0                   1
15                         0                   0                   1
16                         0                   0                   1
17                         0                   0                   1
18                         0                   0                   1
19                         0                   0                   1
20                         0                   0                   1
21                         0                   0                   1
22                         0                   0                   1
23                         0                   0                   1
24                         0                   0                   1
25                         0                   0                   1
26                         0                   0                   1
27                         0                   0                   1
28                         0                   0                   1
29                         0                   0                   1
...                      ...                 ...                 ...
90532                      0                   0                   0
90533                      0                   0                   0
90534                      0                   0                   0
90535                      0                   0                   0
90536                      0                   0                   0
90537                      0                   0                   0
90538                      0                   0                   0
90539                      0                   0                   0
90540                      0                   0                   0
90541                      0                   0                   0
90542                      0                   0                   0
90543                      0                   0                   0
90544                      0                   0                   0
90545                      0                   0                   0
90546                      0                   0                   0
90547                      0                   0                   0
90548                      0                   0                   0
90549                      0                   0                   0
90550                      0                   0                   0
90551                      0                   0                   0
90552                      0                   0                   0
90553                      0                   0                   0
90554                      0                   0                   0
90555                      0                   0                   0
90556                      0                   0                   0
90557                      0                   0                   0
90558                      0                   0                   0
90559                      0                   0                   0
90560                      0                   0                   0
90561                      0                   0                   0

[90562 rows x 10 columns]

In [18]:
# df = pd.get_dummies(df, drop_first=True)
df = pd.get_dummies(df)
df

,number,last_update,available_bike_stands,available_bikes,total_bike_stands,weather_desc_Clear,weather_desc_Clouds,weather_desc_Drizzle,weather_desc_Mist,weather_desc_Rain
0,2,1551726000,15,5,20,0,0,0,0,1
1,3,1551726000,19,1,20,0,0,0,0,1
2,4,1551726000,20,0,20,0,0,0,0,1
3,5,1551726000,11,29,40,0,0,0,0,1
4,6,1551726000,16,4,20,0,0,0,0,1
5,7,1551726000,9,19,28,0,0,0,0,1
6,8,1551726000,15,15,30,0,0,0,0,1
7,9,1551726000,5,19,24,0,0,0,0,1
8,10,1551726000,7,9,16,0,0,0,0,1
9,11,1551726000,30,0,30,0,0,0,0,1
10,12,1551726000,16,4,20,0,0,0,0,1
11,13,1551726000,29,1,30,0,0,0,0,1
12,14,1551726000,5,25,30,0,0,0,0,1
13,15,1551726000,16,0,16,0,0,0,0,1
14,16,1551726000,4,16,20,0,0,0,0,1
15,17,1551726000,18,2,20,0,0,0,0,1
16,18,1551726000,24,6,30,0,0,0,0,1
17,19,1551726000,30,0,30,0,0,0,0,1
18,21,1551726000,4,26,30,0,0,0,0,1
19,22,1551726000,1,19,20,0,0,0,0,1
20,23,1551726000,2,28,30,0,0,0,0,1
21,24,1551726000,14,6,20,0,0,0,0,1
22,25,1551726000,28,2,30,0,0,0,0,1
23,26,1551726000,3,17,20,0,0,0,0,1
24,27,1551726000,18,2,20,0,0,0,0,1
25,28,1551726000,26,4,30,0,0,0,0,1
26,29,1551726000,23,6,29,0,0,0,0,1
27,30,1551726000,18,2,20,0,0,0,0,1
28,31,1551726000,14,6,20,0,0,0,0,1
29,32,1551726000,7,23,30,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...
90532,86,1555138800,3,35,38,0,1,0,0,0
90533,87,1555138800,12,26,38,0,1,0,0,0
90534,88,1555138800,4,26,30,0,1,0,0,0
90535,89,1555138800,38,1,39,0,1,0,0,0
90536,90,1555138800,35,5,40,0,1,0,0,0
90537,91,1555138800,10,20,30,0,1,0,0,0
90538,92,1555138800,0,40,40,0,1,0,0,0
90539,93,1555138800,0,40,40,0,1,0,0,0
90540,94,1555138800,11,29,40,0,1,0,0,0
90541,95,1555138800,7,33,40,0,1,0,0,0
90542,96,1555138800,15,15,30,0,1,0,0,0
90543,97,1555138800,13,27,40,0,1,0,0,0
90544,98,1555138800,40,0,40,0,1,0,0,0
90545,99,1555138800,28,2,30,0,1,0,0,0
90546,100,1555138800,0,25,25,0,1,0,0,0
90547,101,1555138800,22,8,30,0,1,0,0,0
90548,102,1555138800,12,28,40,0,1,0,0,0
90549,103,1555138800,39,1,40,0,1,0,0,0
90550,104,1555138800,26,14,40,0,1,0,0,0
90551,105,1555138800,25,11,36,0,1,0,0,0
90552,106,1555138800,15,25,40,0,1,0,0,0
90553,107,1555138800,30,10,40,0,1,0,0,0
90554,108,1555138800,39,1,40,0,1,0,0,0
90555,109,1555138800,9,20,29,0,1,0,0,0
90556,110,1555138800,30,10,40,0,1,0,0,0
90557,111,1555138800,26,14,40,0,1,0,0,0
90558,112,1555138800,6,24,30,0,1,0,0,0
90559,113,1555138800,40,0,40,0,1,0,0,0
90560,114,1555138800,38,2,40,0,1,0,0,0
90561,115,1555138800,2,28,30,0,1,0,0,0

In [19]:
X = df_all[features]
y = df_all.available_bikes

In [20]:
multiple_linreg = LinearRegression().fit(X, y)

print("\nIntercept: \n", multiple_linreg.intercept_)
print("Features and coeficients:", list(zip(features, multiple_linreg.coef_)))

Intercept:
 8.624923708566712e-08
Features and coeficients: [('available_bikes', 0.666666666666646), ('available_bike_stands', -0.33333333333342324), ('last_update', -5.551115123125783e-17), ('total_bike_stands', 0.3333333333332543), ('weather_desc__Clear', 1.5137483030872435e-15), ('weather_desc__Clouds', -7.992825236440232e-17), ('weather_desc__Drizzle', 2.3530227130948252e-15), ('weather_desc__Mist', -3.4406628434207246e-15), ('weather_desc__Rain', -3.4376742167065133e-16)]

In [21]:
multiple_linreg_predictions = multiple_linreg.predict(X[features])

print("\nPredictions with multiple linear regression: \n")
actual_vs_predicted_multiplelinreg = pd.concat([df, pd.DataFrame(multiple_linreg_predictions, columns=['Predicted'])], axis=1)
print(actual_vs_predicted_multiplelinreg)

Predictions with multiple linear regression:

       number  last_update  available_bike_stands  available_bikes  \
0           2   1551726000                     15                5
1           3   1551726000                     19                1
2           4   1551726000                     20                0
3           5   1551726000                     11               29
4           6   1551726000                     16                4
5           7   1551726000                      9               19
6           8   1551726000                     15               15
7           9   1551726000                      5               19
8          10   1551726000                      7                9
9          11   1551726000                     30                0
10         12   1551726000                     16                4
11         13   1551726000                     29                1
12         14   1551726000                      5               25
13         15   1551726000                     16                0
14         16   1551726000                      4               16
15         17   1551726000                     18                2
16         18   1551726000                     24                6
17         19   1551726000                     30                0
18         21   1551726000                      4               26
19         22   1551726000                      1               19
20         23   1551726000                      2               28
21         24   1551726000                     14                6
22         25   1551726000                     28                2
23         26   1551726000                      3               17
24         27   1551726000                     18                2
25         28   1551726000                     26                4
26         29   1551726000                     23                6
27         30   1551726000                     18                2
28         31   1551726000                     14                6
29         32   1551726000                      7               23
...       ...          ...                    ...              ...
90532      86   1555138800                      3               35
90533      87   1555138800                     12               26
90534      88   1555138800                      4               26
90535      89   1555138800                     38                1
90536      90   1555138800                     35                5
90537      91   1555138800                     10               20
90538      92   1555138800                      0               40
90539      93   1555138800                      0               40
90540      94   1555138800                     11               29
90541      95   1555138800                      7               33
90542      96   1555138800                     15               15
90543      97   1555138800                     13               27
90544      98   1555138800                     40                0
90545      99   1555138800                     28                2
90546     100   1555138800                      0               25
90547     101   1555138800                     22                8
90548     102   1555138800                     12               28
90549     103   1555138800                     39                1
90550     104   1555138800                     26               14
90551     105   1555138800                     25               11
90552     106   1555138800                     15               25
90553     107   1555138800                     30               10
90554     108   1555138800                     39                1
90555     109   1555138800                      9               20
90556     110   1555138800                     30               10
90557     111   1555138800                     26               14
90558     112   1555138800                      6               24
90559     113   1555138800                     40                0
90560     114   1555138800                     38                2
90561     115   1555138800                      2               28

       total_bike_stands  weather_desc_Clear  weather_desc_Clouds  \
0                     20                   0                    0
1                     20                   0                    0
2                     20                   0                    0
3                     40                   0                    0
4                     20                   0                    0
5                     28                   0                    0
6                     30                   0                    0
7                     24                   0                    0
8                     16                   0                    0
9                     30                   0                    0
10                    20                   0                    0
11                    30                   0                    0
12                    30                   0                    0
13                    16                   0                    0
14                    20                   0                    0
15                    20                   0                    0
16                    30                   0                    0
17                    30                   0                    0
18                    30                   0                    0
19                    20                   0                    0
20                    30                   0                    0
21                    20                   0                    0
22                    30                   0                    0
23                    20                   0                    0
24                    20                   0                    0
25                    30                   0                    0
26                    29                   0                    0
27                    20                   0                    0
28                    20                   0                    0
29                    30                   0                    0
...                  ...                 ...                  ...
90532                 38                   0                    1
90533                 38                   0                    1
90534                 30                   0                    1
90535                 39                   0                    1
90536                 40                   0                    1
90537                 30                   0                    1
90538                 40                   0                    1
90539                 40                   0                    1
90540                 40                   0                    1
90541                 40                   0                    1
90542                 30                   0                    1
90543                 40                   0                    1
90544                 40                   0                    1
90545                 30                   0                    1
90546                 25                   0                    1
90547                 30                   0                    1
90548                 40                   0                    1
90549                 40                   0                    1
90550                 40                   0                    1
90551                 36                   0                    1
90552                 40                   0                    1
90553                 40                   0                    1
90554                 40                   0                    1
90555                 29                   0                    1
90556                 40                   0                    1
90557                 40                   0                    1
90558                 30                   0                    1
90559                 40                   0                    1
90560                 40                   0                    1
90561                 30                   0                    1

       weather_desc_Drizzle  weather_desc_Mist  weather_desc_Rain  \
0                         0                  0                  1
1                         0                  0                  1
2                         0                  0                  1
3                         0                  0                  1
4                         0                  0                  1
5                         0                  0                  1
6                         0                  0                  1
7                         0                  0                  1
8                         0                  0                  1
9                         0                  0                  1
10                        0                  0                  1
11                        0                  0                  1
12                        0                  0                  1
13                        0                  0                  1
14                        0                  0                  1
15                        0                  0                  1
16                        0                  0                  1
17                        0                  0                  1
18                        0                  0                  1
19                        0                  0                  1
20                        0                  0                  1
21                        0                  0                  1
22                        0                  0                  1
23                        0                  0                  1
24                        0                  0                  1
25                        0                  0                  1
26                        0                  0                  1
27                        0                  0                  1
28                        0                  0                  1
29                        0                  0                  1
...                     ...                ...                ...
90532                     0                  0                  0
90533                     0                  0                  0
90534                     0                  0                  0
90535                     0                  0                  0
90536                     0                  0                  0
90537                     0                  0                  0
90538                     0                  0                  0
90539                     0                  0                  0
90540                     0                  0                  0
90541                     0                  0                  0
90542                     0                  0                  0
90543                     0                  0                  0
90544                     0                  0                  0
90545                     0                  0                  0
90546                     0                  0                  0
90547                     0                  0                  0
90548                     0                  0                  0
90549                     0                  0                  0
90550                     0                  0                  0
90551                     0                  0                  0
90552                     0                  0                  0
90553                     0                  0                  0
90554                     0                  0                  0
90555                     0                  0                  0
90556                     0                  0                  0
90557                     0                  0                  0
90558                     0                  0                  0
90559                     0                  0                  0
90560                     0                  0                  0
90561                     0                  0                  0

          Predicted
0      5.000000e+00
1      1.000000e+00
2      1.077623e-10
3      2.900000e+01
4      4.000000e+00
5      1.900000e+01
6      1.500000e+01
7      1.900000e+01
8      9.000000e+00
9      1.060730e-10
10     4.000000e+00
11     1.000000e+00
12     2.500000e+01
13     1.084374e-10
14     1.600000e+01
15     2.000000e+00
16     6.000000e+00
17     1.060730e-10
18     2.600000e+01
19     1.900000e+01
20     2.800000e+01
21     6.000000e+00
22     2.000000e+00
23     1.700000e+01
24     2.000000e+00
25     4.000000e+00
26     6.000000e+00
27     2.000000e+00
28     6.000000e+00
29     2.300000e+01
...             ...
90532  3.500000e+01
90533  2.600000e+01
90534  2.600000e+01
90535  1.000000e+00
90536  5.000000e+00
90537  2.000000e+01
90538  4.000000e+01
90539  4.000000e+01
90540  2.900000e+01
90541  3.300000e+01
90542  1.500000e+01
90543  2.700000e+01
90544 -8.506270e-11
90545  2.000000e+00
90546  2.500000e+01
90547  8.000000e+00
90548  2.800000e+01
90549  1.000000e+00
90550  1.400000e+01
90551  1.100000e+01
90552  2.500000e+01
90553  1.000000e+01
90554  1.000000e+00
90555  2.000000e+01
90556  1.000000e+01
90557  1.400000e+01
90558  2.400000e+01
90559 -8.506270e-11
90560  2.000000e+00
90561  2.800000e+01

[90562 rows x 11 columns]

In [22]:
#This function is used repeatedly to compute all metrics
def printMetrics(testActualVal, predictions):
    #classification evaluation measures
    print('\n==============================================================================')
    print("MAE: ", metrics.mean_absolute_error(testActualVal, predictions))
    #print("MSE: ", metrics.mean_squared_error(testActualVal, predictions))
    print("RMSE: ", metrics.mean_squared_error(testActualVal, predictions)**0.5)
    print("R2: ", metrics.r2_score(testActualVal, predictions))

In [23]:
printMetrics(y, multiple_linreg_predictions)

==============================================================================
MAE:  4.199655013674659e-11
RMSE:  4.915303657284433e-11
R2:  1.0

## Evaluation with train/test split

In [24]:
# Split the data into train and test sets
# Take a third (random) data samples as test data, rest as training data
# Note that this training set if very small and the model will not be very reliable due to this sample size problem.
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print("Training data:\n", pd.concat([X_train, y_train], axis=1))
print("\nTest data:\n", pd.concat([X_test, y_test], axis=1))

Training data:
        available_bikes  available_bike_stands  last_update  total_bike_stands  \
81317                1                     29   1554832800                 30
76036                8                     32   1554663600                 40
57681               20                     20   1554066000                 40
5632                13                     27   1552377600                 40
77288                5                     33   1554703200                 38
85190                1                     35   1554966000                 36
26480               16                      6   1553047200                 22
51538                0                     31   1553864400                 31
73291               16                     14   1554577200                 30
60977                1                     29   1554174000                 30
50999                0                     40   1553846400                 40
32750                0                     30   1553256000                 30
24578                0                     30   1552986000                 30
46023                0                     40   1553688000                 40
26927                3                     26   1553061600                 29
57689               22                      8   1554069600                 30
65963               27                      3   1554339600                 30
61242                1                     19   1554181200                 20
84964                0                     36   1554958800                 36
10698               39                      1   1552539600                 40
33252                0                     35   1553270400                 35
26306                0                     30   1553043600                 30
27559                4                     16   1553083200                 20
12565               33                      7   1552600800                 40
4799                 2                     38   1552352400                 40
77830               26                     14   1554721200                 40
89627               21                     14   1555110000                 35
79362               15                      5   1554771600                 20
36224               23                     17   1553367600                 40
90469                3                     27   1555138800                 30
...                ...                    ...          ...                ...
67424               19                      1   1554386400                 20
48250                5                     20   1553760000                 25
83339                7                     23   1554908400                 30
56654                2                     38   1554033600                 40
35881                3                     27   1553353200                 30
3981                 2                     28   1551978000                 30
3894                31                      9   1551974400                 40
74440                3                     37   1554613200                 40
53156               12                     28   1553918400                 40
12472                0                     40   1552597200                 40
39617               15                      5   1553475600                 20
14157               32                      7   1552651200                 39
70901               16                      4   1554498000                 20
37827                4                     16   1553418000                 20
45988                0                     20   1553688000                 20
43419                0                     38   1553601600                 38
49146               28                     12   1553788800                 40
41495                5                     35   1553533200                 40
66963               11                      9   1554372000                 20
51440                0                     38   1553860800                 38
47224                0                     32   1553727600                 32
13930               38                      2   1552644000                 40
7420                 8                     22   1552435200                 30
75424               27                      3   1554645600                 30
19149               10                     30   1552809600                 40
52028                0                     40   1553878800                 40
55442                4                     16   1553997600                 20
83025               12                     18   1554897600                 30
17266                0                     40   1552748400                 40
6162                 1                     37   1552395600                 38

       weather_desc__Clear  weather_desc__Clouds  weather_desc__Drizzle  \
81317                    0                     1                      0
76036                    0                     1                      0
57681                    0                     1                      0
5632                     0                     0                      0
77288                    0                     0                      0
85190                    0                     1                      0
26480                    0                     1                      0
51538                    0                     1                      0
73291                    1                     0                      0
60977                    0                     1                      0
50999                    0                     1                      0
32750                    0                     0                      0
24578                    0                     0                      1
46023                    0                     1                      0
26927                    0                     1                      0
57689                    0                     1                      0
65963                    0                     0                      0
61242                    0                     1                      0
84964                    0                     1                      0
10698                    0                     0                      0
33252                    0                     1                      0
26306                    0                     1                      0
27559                    0                     1                      0
12565                    0                     0                      0
4799                     0                     0                      0
77830                    0                     0                      0
89627                    0                     1                      0
79362                    0                     0                      1
36224                    0                     1                      0
90469                    0                     1                      0
...                    ...                   ...                    ...
67424                    0                     0                      0
48250                    1                     0                      0
83339                    0                     1                      0
56654                    0                     1                      0
35881                    0                     1                      0
3981                     0                     0                      0
3894                     0                     0                      0
74440                    0                     0                      0
53156                    0                     1                      0
12472                    0                     0                      0
39617                    0                     1                      0
14157                    0                     1                      0
70901                    0                     0                      0
37827                    0                     1                      0
45988                    0                     1                      0
43419                    0                     1                      0
49146                    1                     0                      0
41495                    0                     1                      0
66963                    0                     1                      0
51440                    0                     1                      0
47224                    0                     1                      0
13930                    0                     1                      0
7420                     0                     0                      0
75424                    0                     1                      0
19149                    0                     1                      0
52028                    0                     1                      0
55442                    0                     1                      0
83025                    0                     1                      0
17266                    0                     0                      0
6162                     0                     0                      0

       weather_desc__Mist  weather_desc__Rain  available_bikes
81317                   0                   0                1
76036                   0                   0                8
57681                   0                   0               20
5632                    0                   1               13
77288                   1                   0                5
85190                   0                   0                1
26480                   0                   0               16
51538                   0                   0                0
73291                   0                   0               16
60977                   0                   0                1
50999                   0                   0                0
32750                   0                   1                0
24578                   0                   0                0
46023                   0                   0                0
26927                   0                   0                3
57689                   0                   0               22
65963                   0                   1               27
61242                   0                   0                1
84964                   0                   0                0
10698                   0                   1               39
33252                   0                   0                0
26306                   0                   0                0
27559                   0                   0                4
12565                   0                   1               33
4799                    0                   1                2
77830                   0                   1               26
89627                   0                   0               21
79362                   0                   0               15
36224                   0                   0               23
90469                   0                   0                3
...                   ...                 ...              ...
67424                   0                   1               19
48250                   0                   0                5
83339                   0                   0                7
56654                   0                   0                2
35881                   0                   0                3
3981                    0                   1                2
3894                    0                   1               31
74440                   1                   0                3
53156                   0                   0               12
12472                   0                   1                0
39617                   0                   0               15
14157                   0                   0               32
70901                   0                   1               16
37827                   0                   0                4
45988                   0                   0                0
43419                   0                   0                0
49146                   0                   0               28
41495                   0                   0                5
66963                   0                   0               11
51440                   0                   0                0
47224                   0                   0                0
13930                   0                   0               38
7420                    0                   1                8
75424                   0                   0               27
19149                   0                   0               10
52028                   0                   0                0
55442                   0                   0                4
83025                   0                   0               12
17266                   0                   1                0
6162                    0                   1                1

[63393 rows x 10 columns]

Test data:
        available_bikes  available_bike_stands  last_update  total_bike_stands  \
16635                3                     18   1552730400                 21
51003               10                     30   1553846400                 40
36927                3                     17   1553389200                 20
33518                0                     30   1553281200                 30
1330                 1                     39   1551798000                 40
26502                0                     40   1553047200                 40
28123                4                     16   1553101200                 20
57483               15                     14   1554062400                 29
38015                8                     32   1553421600                 40
87660                0                     20   1555048800                 20
67371                0                     38   1554382800                 38
81332                1                     31   1554832800                 32
70882                4                     36   1554494400                 40
23823                8                     21   1552964400                 29
85620               18                      4   1554980400                 22
22329               34                      6   1552914000                 40
89012               10                     20   1555092000                 30
43602                0                     30   1553608800                 30
68713               24                     16   1554426000                 40
22200               11                     27   1552910400                 38
31074                9                     31   1553194800                 40
29156                0                     20   1553133600                 20
57420                6                     21   1554058800                 27
84725               30                      0   1554951600                 30
19636                0                     40   1552824000                 40
56908                2                     28   1554044400                 30
85012               12                     28   1554958800                 40
24357                0                     36   1552978800                 36
63040                4                     36   1554238800                 40
33157                0                     40   1553266800                 40
...                ...                    ...          ...                ...
43191                0                     30   1553594400                 30
72305                1                     39   1554544800                 40
47635                0                     16   1553742000                 16
9468                 6                     30   1552500000                 36
6101                28                      2   1552395600                 30
88297                1                     39   1555066800                 40
55884                1                     29   1554012000                 30
81684                1                     39   1554847200                 40
62270               28                      0   1554213600                 28
31443               14                     26   1553205600                 40
8365                10                     20   1552467600                 30
50146                2                     38   1553821200                 40
72730               17                     23   1554559200                 40
38029               16                      4   1553425200                 20
8981                23                      5   1552485600                 28
37671                1                     29   1553410800                 30
77115                0                     16   1554699600                 16
10285                0                     20   1552528800                 20
14081                0                     35   1552647600                 35
78046               20                     10   1554728400                 30
43059                9                     31   1553587200                 40
39989                1                     19   1553486400                 20
27377                2                     38   1553076000                 40
73057                7                     13   1554570000                 20
65965                1                     39   1554339600                 40
29710               18                     22   1553151600                 40
10848               10                      6   1552546800                 16
64826               12                      8   1554303600                 20
9176                 4                     16   1552492800                 20
21053                7                     33   1552874400                 40

       weather_desc__Clear  weather_desc__Clouds  weather_desc__Drizzle  \
16635                    0                     0                      0
51003                    0                     1                      0
36927                    0                     1                      0
33518                    0                     1                      0
1330                     0                     1                      0
26502                    0                     1                      0
28123                    0                     0                      0
57483                    0                     1                      0
38015                    0                     1                      0
87660                    0                     1                      0
67371                    0                     1                      0
81332                    0                     1                      0
70882                    0                     0                      0
23823                    0                     1                      0
85620                    0                     1                      0
22329                    0                     1                      0
89012                    0                     1                      0
43602                    0                     1                      0
68713                    0                     1                      0
22200                    0                     0                      1
31074                    0                     1                      0
29156                    0                     1                      0
57420                    0                     1                      0
84725                    0                     1                      0
19636                    0                     0                      0

In [25]:
# Train on the training sample and test on the test sample.
linreg = LinearRegression().fit(X_train, y_train)
# Print the weights learned for each feature.
#print(linreg_train.coef_)
print("Features and coeficients:", list(zip(features, linreg.coef_)))

Features and coeficients: [('available_bikes', 0.6666666666665384), ('available_bike_stands', -0.3333333333334026), ('last_update', 5.551115123125783e-17), ('total_bike_stands', 0.33333333333321624), ('weather_desc__Clear', -4.619999266605467e-16), ('weather_desc__Clouds', 4.568445069491977e-15), ('weather_desc__Drizzle', 1.389616015096375e-15), ('weather_desc__Mist', -9.218057468201292e-15), ('weather_desc__Rain', 3.725515943927565e-15)]

In [26]:
# Predicted price on training set
train_predictions = linreg.predict(X_train)
print("Actual values of training:\n", y_train)
print("Predictions on training:", train_predictions)
printMetrics(y_train, train_predictions)

Actual values of training:
 81317     1
76036     8
57681    20
5632     13
77288     5
85190     1
26480    16
51538     0
73291    16
60977     1
50999     0
32750     0
24578     0
46023     0
26927     3
57689    22
65963    27
61242     1
84964     0
10698    39
33252     0
26306     0
27559     4
12565    33
4799      2
77830    26
89627    21
79362    15
36224    23
90469     3
         ..
67424    19
48250     5
83339     7
56654     2
35881     3
3981      2
3894     31
74440     3
53156    12
12472     0
39617    15
14157    32
70901    16
37827     4
45988     0
43419     0
49146    28
41495     5
66963    11
51440     0
47224     0
13930    38
7420      8
75424    27
19149    10
52028     0
55442     4
83025    12
17266     0
6162      1
Name: available_bikes, Length: 63393, dtype: int64
Predictions on training: [ 1.00000000e+00  8.00000000e+00  2.00000000e+01 ...  1.20000000e+01
 -5.05425083e-11  1.00000000e+00]

==============================================================================
MAE:  4.193741490568568e-11
RMSE:  4.910463274638963e-11
R2:  1.0

In [27]:
# Predicted price on test set
test_predictions = linreg.predict(X_test)
print("Actual values of test:\n", y_test)
print("Predictions on test:", test_predictions)
printMetrics(y_test, test_predictions)

Actual values of test:
 16635     3
51003    10
36927     3
33518     0
1330      1
26502     0
28123     4
57483    15
38015     8
87660     0
67371     0
81332     1
70882     4
23823     8
85620    18
22329    34
89012    10
43602     0
68713    24
22200    11
31074     9
29156     0
57420     6
84725    30
19636     0
56908     2
85012    12
24357     0
63040     4
33157     0
         ..
43191     0
72305     1
47635     0
9468      6
6101     28
88297     1
55884     1
81684     1
62270    28
31443    14
8365     10
50146     2
72730    17
38029    16
8981     23
37671     1
77115     0
10285     0
14081     0
78046    20
43059     9
39989     1
27377     2
73057     7
65965     1
29710    18
10848    10
64826    12
9176      4
21053     7
Name: available_bikes, Length: 27169, dtype: int64
Predictions on test: [ 3. 10.  3. ... 12.  4.  7.]

==============================================================================
MAE:  4.201949266732135e-11
RMSE:  4.916971587036695e-11
R2:  1.0

In [28]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [29]:
with open('model.pkl', 'wb') as handle:
    pickle.dump(model, handle, pickle.HIGHEST_PROTOCOL)